version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.9

        steps:
            - checkout

            - restore_cache:
                  keys:
                      - gatekeeper-{{ .Branch }}-{{ checksum "package.json" }}

            - run:
                  name: Install dependencies
                  command: npm install

            - save_cache:
                  key: gatekeeper-{{ .Branch}}-{{ checksum "package.json" }}
                  paths:
                      - node_modules

            - run:
                  name: Run tests
                  command: npm run test
